### ISSUE TITLE
0107 TODO

### ISSUE THREAD

**Issue by williiam** [williiam/hololens_aim_bot#3]
1. GAZE時 disable 手的rayCast
2. GAZE時 ONHOVER 變大?
3. 計分顯示 hit/時間
4. rayBall被gaze時不應該有動畫

**Comment by YJack0000** [comment]
On hover 可以參考: [這個](https://www.youtube.com/watch?v=gWFOw_yb9vY&t=138s)影片後面的材質也還不錯
